title: <p align="center"> Kharis Syaifullah </p>

logo:"/images/myprofilnew.jpg?raw=true"

description:
  <p align="center">
  <a href="https://instagram.com/sya.kharis?igshid=ZDdkNTZiNTM=">Instagram</a> |
  <a href="https://www.linkedin.com/in/kharis-syaifullah-57a92b26a">LinkedIn</a> |
  <a href="https://github.com/syaifullah06">GitHub</a>
  </p>
  
  <p align="justify">
  I am currently pursuing a bachelor's degree in mathematics study program at the Faculty of Mathematics and Natural Sciences, State University of Malang.
  <br><br>
  I am currently a Certified independent Study at Zenius with a focus on Data Analyst.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
